//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntrLibrary.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConfiguracionEntity : DbContext
    {
        public ConfiguracionEntity()
            : base("name=ConfiguracionEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cuentas> cuentas { get; set; }
        public virtual DbSet<lineas> lineas { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<menuRoles> menuRoles { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<tintas> tintas { get; set; }
        public virtual DbSet<tiposDocumentos> tiposDocumentos { get; set; }
        public virtual DbSet<ubicaciones> ubicaciones { get; set; }
        public virtual DbSet<ubicacionesDetalle> ubicacionesDetalle { get; set; }
        public virtual DbSet<ubicacionesDetalleLote> ubicacionesDetalleLote { get; set; }
    }
}
