//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntrLibrary.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controladoras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Controladoras()
        {
            this.menu = new HashSet<menu>();
            this.MetodosControladora = new HashSet<MetodosControladora>();
        }
    
        public int idControladora { get; set; }
        public string Path { get; set; }
        public string NombreControladora { get; set; }
        public string descripcionControladora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu> menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetodosControladora> MetodosControladora { get; set; }
    }
}
