//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntrLibrary.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentas
    {
        public int idCuenta { get; set; }
        public int idusuario { get; set; }
        public string Usuario { get; set; }
        public string pass { get; set; }
    }
}
