//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntrLibrary.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodosControladora
    {
        public int idMetodo { get; set; }
        public string metodo { get; set; }
        public string descripcionMetodo { get; set; }
        public string nombreMostrar { get; set; }
        public string vista { get; set; }
        public int idControladora { get; set; }
    
        public virtual Controladoras Controladoras { get; set; }
    }
}
