//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntrLibrary.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacionesDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ubicacionesDetalle()
        {
            this.ubicacionesDetalleLote = new HashSet<ubicacionesDetalleLote>();
        }
    
        public int idUbicacionDetalle { get; set; }
        public int idubicacion { get; set; }
        public string desDetalle { get; set; }
        public bool contieneTintas { get; set; }
        public bool contieneColores { get; set; }
    
        public virtual ubicaciones ubicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ubicacionesDetalleLote> ubicacionesDetalleLote { get; set; }
    }
}
