//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerAppServices.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class colores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public colores()
        {
            this.colorDetalle = new HashSet<colorDetalle>();
            this.inventarioMovimientosDetalle = new HashSet<inventarioMovimientosDetalle>();
            this.ubicacionesDetalleLote = new HashSet<ubicacionesDetalleLote>();
        }
    
        public int idColor { get; set; }
        public string nombreColor { get; set; }
        public string codigoColor { get; set; }
        public int idUsuarioRegistra { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime fechaRegistro { get; set; }
        public bool inactivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<colorDetalle> colorDetalle { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventarioMovimientosDetalle> inventarioMovimientosDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ubicacionesDetalleLote> ubicacionesDetalleLote { get; set; }
    }
}
