//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventariosMovimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventariosMovimientos()
        {
            this.inventarioMovimientosDetalle = new HashSet<inventarioMovimientosDetalle>();
        }
    
        public int idMovimiento { get; set; }
        public int idUsuarioregistra { get; set; }
        public int numeroMovimiento { get; set; }
        public int fechaMovimiento { get; set; }
        public int signoMovimiento { get; set; }
        public string descripcionMovimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventarioMovimientosDetalle> inventarioMovimientosDetalle { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
