//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerAppServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inv001Entities : DbContext
    {
        public inv001Entities()
            : base("name=inv001Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<tiposDocumentos> tiposDocumentos { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<ubicaciones> ubicaciones { get; set; }
        public virtual DbSet<ubicacionesDetalle> ubicacionesDetalle { get; set; }
        public virtual DbSet<colorDetalle> colorDetalle { get; set; }
        public virtual DbSet<colores> colores { get; set; }
        public virtual DbSet<cuentas> cuentas { get; set; }
        public virtual DbSet<inventarioMovimientosDetalle> inventarioMovimientosDetalle { get; set; }
        public virtual DbSet<inventariosMovimientos> inventariosMovimientos { get; set; }
        public virtual DbSet<lineas> lineas { get; set; }
        public virtual DbSet<tintas> tintas { get; set; }
        public virtual DbSet<ubicacionesDetalleLote> ubicacionesDetalleLote { get; set; }
        public virtual DbSet<Controladoras> Controladoras { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<menuRoles> menuRoles { get; set; }
        public virtual DbSet<MetodosControladora> MetodosControladora { get; set; }
    }
}
