//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menuRoles
    {
        public int idMenuRole { get; set; }
        public int idRole { get; set; }
        public int idMenu { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual roles roles { get; set; }
    }
}
