//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerAppServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int idUsuario { get; set; }
        public int idTipoDocumento { get; set; }
        public string identificacion { get; set; }
        public string nombrePrimero { get; set; }
        public string nombreSegundo { get; set; }
        public string apellidoPrimero { get; set; }
        public string apellidoSegundo { get; set; }
        public int idRole { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual tiposDocumentos tiposDocumentos { get; set; }
    }
}
